version: '3.6'
services:
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    container_name: mosquitto
    restart: always
    volumes:
      - ./mosquitto/conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data/:/mosquitto/data/
      - ./mosquitto/log/:/mosquitto/log/
    ports:
      - 1883:1883
      - 9001:9001
  
  influxdb:
    image: influxdb:2.7-alpine
    container_name: influxdb
    restart: always
    env_file:
      - .env
    volumes:
      - ./influxdb_storage:/var/lib/influxdb2:rw
    ports:
      - 8086:8086

  telegraf:
    image: telegraf:1.26-alpine
    container_name: telegraf
    restart: always
    volumes:
      - ${TELEGRAF_INIT_CFG_PATH}:/etc/telegraf/telegraf.conf:ro
    env_file:
      - .env
    depends_on:
      - influxdb
    ports:
     - 8125:8125